
spring:
  main:
    banner-mode: off
    timezone: Asia/Ho_Chi_Minh

  jackson:
    time-zone: Asia/Ho_Chi_Minh
    serialization:
      write-dates-as-timestamps: false

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth/v3/api-docs
      - name: user-service
        url: /user/v3/api-docs

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS,Asia/Ho_Chi_Minh

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info
