server:
  port: ${AUTH_SERVICE_PORT:8081}

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${AUTH_DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    jwt:
      issuer: cinema-auth
      access-token-expiration: 900
      refresh-token-expiration: 2592000
      algorithm: RS256

    cookie:
      access-token-name: ACCESS_TOKEN
      refresh-token-name: REFRESH_TOKEN
      secure: false
      http-only: true
      same-site: Lax

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info