
spring:
  cloud:
    discovery:
      enabled: false
    loadbalancer:
      enabled: false

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: false
